### ISSUE TITLE
Security: HTTP Request and Response splitting

### ISSUE THREAD

**Issue by makishvili** [baby-loris/bla#104]
https://www.owasp.org/index.php/HTTP_Response_Splitting
Кажется, защита от этой атаки должна быть встроена в ядро bla.

Чтобы не использовать кастомные санитайзеры в каждом проекте, предполагаем, это можно сделать в `bla/lib/api-method.js`:

```javascript
exec: function (params, request, api) {
        params = this._sanitize(params) || {};
// ...
},

/**
 * Очищает параметры запроса от небезопасных символов
 *
 * @param {Object} params параметры запроса
 * @returns {Object}
 */
_sanitize: function (params) {
    Object.keys(params).forEach(function (paramKey) {
        var paramValue = params[paramKey];

        if (typeof paramValue === 'string') {
            paramValue = paramValue
                .replace(/\r/g, '')
                .replace(/\n/g, '')
                .replace(/\x00/g, '')
                .replace(/%0a/g, '')
                .replace(/%0d/g, '')
                .replace(/\?/g, '%3F');
        }

        params[paramKey] = paramValue;
    });

    return params;
}
```

**Comment by tarmolov** [comment]
https://github.com/baby-loris/bla/issues/91

**Comment by tarmolov** [comment]
Not everyone needs a sanitizer. However, you can implement your own validator.

See documentation for more details:
https://github.com/baby-loris/bla/blob/master/REFERENCE.md#options

**Comment by tarmolov** [comment]
I'll close the issue. However, if you implement a sanitizer validator, feel free to open pr ;)
