### ISSUE TITLE
Call action via vow.invoke

### ISSUE THREAD

**Issue by dfilatov** [baby-loris/bla#105]
https://github.com/baby-loris/bla/blob/master/lib/api-method.js#L128

Currently, if something has gone wrong in action, everything fails. It's better to localize failure area just rejecting promise. It's easy to achieve using `vow.invoke`.

**Comment by tarmolov** [comment]
We did it on purpose because it was hard to debug api methods. Now if you make a mistake (for example, a syntax error), you'll see it in a console.

I think if you have some code in an api method which generates an error in runtime, you should add an extra check there.

//cc @lemmy-

**Comment by dfilatov** [comment]
@tarmolov Currently If one of batched methods fails in such manner I get an error for all others. It's unsuitable.

**Comment by dfilatov** [comment]
ping

**Comment by tarmolov** [comment]
As I wrote above, if we wrap api call with a promise, a developer won't see runtime errors in nodejs console. It looks bad, too.

You can wrap code in api method with a promise manually:
```javascript
var method = new bla.ApiMethod({
    name: 'method',
    action: function (params, request, api) {
        return vow.resolve().then(function () {
            // put all your stuff here
        });
    }
});
```
But I think you'll come to hate me for such suggestion ^^

So, my another suggestion is to add an extra option `mode` to the Api class. 

By default, `mode` is set to `development` and bla will throw exceptions (its current behavior). 
If you set `mode` to `production`, all api calls will be wrapped to promises.

Does it work for you?
