### ISSUE TITLE
bla 2.0

### ISSUE THREAD

**Issue by tarmolov** [baby-loris/bla#114]
It's time to rethink the library and take into account all suggestions, ideas, and advice.

What's new should be added/changed/removed in 2.0?
1. Use ES6 promises instead of `vow`.
2. Add a more profound param validation.
3. Add a debug mode.
4. Add api method name to ApiError message.
5. Add "hooks" such as `beforeRequestSend` and `afterResponseReceived` to the client side.
6. It's not possible to stream a file or to response with json without data/error wrappers.
7. Metainformation for response/error.
8. Add all errors listed in [http statuses](https://github.com/prettymuchbryce/node-http-status).
9. Global hook in Api for resolving/rejecting methods.

/cc @lemmy- @razetdinov @dfilatov @twoRoger @zloylos

**Comment by zloylos** [comment]
I have some issues for bla 2.0.

1. Validation params by scheme. This is important part for using complex API handlers. Now I have to validate them manually.
2. Request method. This is important part of any REST API: UPDATE, DELETE, POST, GET. Now this is impossible. For example: POST to api/book for create book, DELETE api/book?id=1, UPDATE and etc.
3. Very important debug mode. Really…
4. I want to have also global hooks for each requests on a client and server sides. Why? What if I want use protobuf instead JSON?

**Comment by razetdinov** [comment]
I need a versioning support with VERSION_MISMATCH error thrown when client and server versions differ.

**Comment by tarmolov** [comment]
@lemmy- and I have aggregated all wishes and we have got the following list:

0. Divide client side to separate modules.
1. Hooks for client sides.
2. Debug mode.
3. Using HTTP statuses for errors.
4. Validation plugins.

It makes it possible to solve them in v1 without breaking backward compatibility. We believe that it solves the most of our requests.

**Comment by zloylos** [comment]
* Examples for dockpage.
We can add param `examples` which contains set of valid set of parameters.
And then show them into dockpage or playground.

```js
module.exports = new bla.ApiMethod({
  name: 'bla-method',
  description: 'Change user name',
  examples: [
    {user_id: 1, new_name: 'Vasya'},
    {user_id: 2, new_name: 'Petr'}
  ],
  params: {
    user_id: {type: 'number', required: true},
    new_name: {type: 'string', required: true}
  },
  action: () => {}
});
```

Examples can be stored in `bla-method.api.examples.json', for example.
``` examples: require('./bla-method.api.examples')```

**Comment by tarmolov** [comment]
Firstly, we decide to solve 3 and 5 issues. #115 #116
