### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by tarmolov** [baby-loris/bla#115]
Decide to use the same debug behavior as [nock does](https://github.com/node-nock/nock#debugging).

```
DEBUG=bla.* node app_with_bla.js
```

When debug mode is turned on:
1. All bla method executions should be logged: name and parameters.
2. All exceptions should be logged as well.
3. To all errors method name should be added (validators and exec).

relates to #110

**Comment by tarmolov** [comment]
@lemmy- is a little bit busy.
@zloylos do you want to help? ;)

**Comment by zloylos** [comment]
I'll try
